# Site
name: 'Genezis'
description: 'Lets Learn and Explore together'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
# baseurl: /genezis.github.io
baseurl: /
disqus: 'Genesis'
google_analytics: 'UA-198499883-1'
email: '#'
mailchimp-list: 'https://github.us10.list-manage.com/subscribe/post?u=145fd0db654a848f2210027e9&amp;id=9f918ad6cc'
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    prince:
      name:           prince
      site:           #
      avatar:         assets/images/x-logo.jpg
      bio:            "Author of Genezis. A technical consultant with experience in computer logics, design and development."
      email:          #
      twitter:        https://twitter.com/prince_9210
    
    grim:
      name:           grim
      site:           #
      avatar:         assets/images/grim.png
      bio:            "Hi, I am grim, the author and co-founder of Genesis"
      email:          #
      twitter:        #

# Defaults
defaults:

# all posts
- scope:
    path: "_posts"
  values:
    layout: post
    # author: prince
    # avatar: /assets/images/avatar.jpg
    
# all pages
- scope:
    path: "_pages"
  values:
    layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 5

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]