# Site
name: 'Genezis'
description: 'Genezis is a free jekyll theme'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
# baseurl: /genezis.github.io
baseurl: /
disqus: 'Genesis'
email: '#'
mailchimp-list: 'https://github.us10.list-manage.com/subscribe/post?u=145fd0db654a848f2210027e9&amp;id=9f918ad6cc'
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    prince:
      name:           prince
      site:           #
      avatar:         assets/images/avatar.jpg
      bio:            "Hi, I am Prince, the author of Genesis, the theme you're currently previewing. I hope you like it!"
      email:          #
      twitter:        #

# Defaults
defaults:

# all posts
- scope:
    path: "_posts"
  values:
    layout: post
    author: prince
    avatar: /assets/images/avatar.jpg
    
# all pages
- scope:
    path: "_pages"
  values:
    layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]